const express = require('express');
const pool = require('../database/pool');
const { authRequired } = require('../middleware/authMiddleware');
const { TITLES, TITLE_BY_ID } = require('../data/titleCatalog');
const router = express.Router();
const normalizeRole = value => ({PLAYER:'default',PARTICIPANT:'default',DEFAULT:'default',MODERATOR:'moderator',ADMIN:'admin',OWNER:'spec.admin','SPEC.ADMIN':'spec.admin'}[String(value||'default').toUpperCase()]||'default');
async function owner(userId){const result=await pool.query(`SELECT p.uuid,p.nickname,t.active_title_id,t.standard_title FROM players p LEFT JOIN pd_player_titles t ON t.player_uuid=p.uuid::uuid WHERE p.auth_user_id=$1 LIMIT 1`,[userId]);return result.rows[0]||null;}
router.get('/',authRequired,async(req,res,next)=>{try{const player=await owner(req.user.id);if(!player?.uuid)return res.status(409).json({message:'Сначала зайдите на сервер, чтобы связать профиль титулов.'});const result=await pool.query('SELECT title_id,unlocked_at FROM pd_unlocked_titles WHERE player_uuid=$1::uuid',[player.uuid]);const unlocked=new Map(result.rows.map(row=>[row.title_id,row.unlocked_at]));res.json({role:normalizeRole(player.standard_title||req.user.role),activeTitleId:player.active_title_id,unlockedCount:result.rows.length,titles:TITLES.map(title=>({...title,unlocked:unlocked.has(title.id),unlockedAt:unlocked.get(title.id)||null}))});}catch(error){next(error);}});
router.post('/',authRequired,async(req,res,next)=>{try{const player=await owner(req.user.id);if(!player?.uuid)return res.status(409).json({message:'Профиль титулов не связан с сервером.'});const titleId=req.body?.titleId===null||req.body?.titleId===''?null:String(req.body?.titleId||'').trim().toLowerCase();if(titleId&&!TITLE_BY_ID.has(titleId))return res.status(400).json({message:'Неизвестный титул.'});if(titleId){const access=await pool.query('SELECT 1 FROM pd_unlocked_titles WHERE player_uuid=$1::uuid AND title_id=$2',[player.uuid,titleId]);if(!access.rows.length)return res.status(403).json({message:'Этот титул ещё не получен.'});}await pool.query('UPDATE pd_player_titles SET active_title_id=$1,updated_at=NOW() WHERE player_uuid=$2::uuid',[titleId,player.uuid]);res.json({message:titleId?`Титул «${TITLE_BY_ID.get(titleId).name}» выбран.`:'Выбран стандартный титул.',activeTitleId:titleId});}catch(error){next(error);}});
module.exports=router;
